### ISSUE TITLE
Very cool. Are prebuilts ready ? We would love to add it into x-cmd

### ISSUE THREAD

**Issue by edwinjhlee** [Wayoung7/firework-rs#1]
Hello, friends. This project is VERY cool.

We would love to add this as a package inside x-cmd.

This is demo of pkg concepts in [gotop in x-cmd](https://x-cmd.com/1min/gotop)

We tend to repackage prebuilt binaries provided by author.

If you don't want to manage prebuilt binaries of various platforms, WASM is also an ideal build target. 

X-cmd has already added wasmer as a package. We will add [wasmtime](https://github.com/bytecodealliance/wasmtime) in x-cmd very soon.

**Comment by Wayoung7** [comment]
Thank you, friend! Sure, you can add this in x-cmd, at any time. Redistribution is always welcomed.
I've release a new version and prebuilt binaries for different platforms also included, and are ready to be repackaged.

**Comment by edwinjhlee** [comment]
AWESOME !
